### PR TITLE
Scrum 91 improve survey

### PR DESCRIPTION
**Pull request by Xinlong-Wu**

### CODE REVIEW

**Review by Eddyhzz — APPROVED** [review]
good

**Comment by wwssllxxGithub** [comment]
good

**Review by c1c4da3300 — APPROVED** [review]

**Review by Valencia-Choi — APPROVED** [review]
Do a great job!

**Review by Universe-E — APPROVED** [review]

**Review by wwssllxxGithub — APPROVED** [review]
looks good to me

**Pull request merged**
